# Generated by Django 5.1.2 on 2024-11-04 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Tutor", "Tutor"),
                    ("Admin", "Admin"),
                    ("Student", "Student"),
                ],
                default="Student",
                help_text="Select the type of user.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text='Enter a username starting with "@" followed by at least three alphanumeric characters.',
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username must start with @ followed by at least three alphanumeric characters (letters, numbers, or underscore).",
                        regex="^@\\w{3,}$",
                    )
                ],
            ),
        ),
    ]
