# Generated by Django 5.1.1 on 2024-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingtutor",
            name="skill",
        ),
        migrations.AddField(
            model_name="pendingtutor",
            name="skills",
            field=models.ManyToManyField(
                related_name="pending_tutors", to="tutorials.skill"
            ),
        ),
    ]
