# Generated by Django 5.1.2 on 2024-12-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_studentrequest_duration_pendingtutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtutor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
